### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by ocefpaf**
@dougalsutherland is `numpy 1.11.*` and `scipy 0.18.*` OK as a minimum? That combination seems to work just fine for re-rendering.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
Hmm. I don't know what the fundamental difference is from #2 here, but it's probably fine (and simpler) to just require slightly higher version numbers. :man_shrugging: 

Should probably bump the build number too.

**Comment by ocefpaf** [comment]
> Hmm. I don't know what the fundamental difference is from #2 here, but it's probably fine (and simpler) to just require slightly higher version numbers. :man_shrugging: 


I have to be honest, I was just lazy to check if all those combinations had a proper solution for conda-smithy to rerender. My guess is that it does b/c you did build this locally, so something else may be wrong. However, this simpler combination of deps are easily solved.

**Comment by rth** [comment]
@ocefpaf @dougalsutherland Thanks a lot for looking into it! The build is green (and the PY3.6 build is there), should this be merged then?

> Should probably bump the build number too.

So when the build number is not incremented would it overwrite the previous build or error at upload time?

**Comment by dougalsutherland** [comment]
@rth Neither; it just won't update the build, leaving the old one in place. That means I think that merging this as-is would also be fine, since there'll be a build 0 that works everywhere, just some of them will have slightly different requirements than others (which is fine).

**Comment by isuruf** [comment]
> just some of them will have slightly different requirements than others (which is fine).

This will be hard to debug if a bug shows up. I recommend bumping the build number.

**Comment by dougalsutherland** [comment]
That's true. @rth, you can do that by check out @ocefpaf's branch locally, add a commit bumping the build number, then `git merge` that onto master and push. Or he might have the button checked where you can push onto his branch and then hit merge on the web UI if you prefer, but since you don't need to rerun CIs there's not a ton of point in doing that.

**Comment by rth** [comment]
> Or he might have the button checked where you can push onto his branch and then hit merge on the web UI if you prefer, but since you don't need to rerun CIs there's not a ton of point in doing that.

Or edit files directly on the Github GUI on his fork without needing to checkout it localy (Github seems to allow it by default now for package maintainers). 

OK, I incremented the build number. Merging. 

Thanks a again for your help @dougalsutherland @ocefpaf !

**Pull request merged**
